### ISSUE TITLE
Delete message from DM or channel by ID

### ISSUE THREAD

**Issue by MattMski** [valzargaming/Yasmin#4]
Hello I use the Yasmin bot and i stumbled upon your fork of it.
I was wondering if you be able to help me out with implementing a way to delete a message based on its ID.

I'd appreciate any sort of help on this, thank you!

**Comment by valzargaming** [comment]
Hi MattMski! I believe that as long as you have a valid instance of the channel that the message is in, deleting the message itself should be pretty easy. Something along the line of:

```
$message = $channel->getMessages()->get($id);
if ($message instanceof \CharlotteDunois\Yasmin\Models\Message) {
    $channel->getMessages()->delete($message->id);
}
```

Message ids by themselves have no reference to the message without a valid guild and channel, though this obviously changes slightly when DMs come into play, in which case the guild becomes @me and the channel becomes the user id of the person being messaged.

Hope this helps!

**Comment by MattMski** [comment]
Hey @valzargaming, thank you for your quick response!

Regarding your code, I have tried this

```
$channel = $message->channel;
$smessage = $channel->getMessages()->get($args);
if ($smessage instanceof \CharlotteDunois\Yasmin\Models\Message) {
	$channel->getMessages()->delete($smessage->id);
}	
```
$args being the message id that i have from Discord. 
Nothing is deleting though nor am I getting any error.

**Comment by valzargaming** [comment]
I have no idea what you are trying to accomplish with your code or the circumstances. In your example you are getting information from $channel from your already (assumed) instance of $message. If you want to delete the message then just use `$message->delete();` as there is no need to fetch the information again. If you don't know the message id yet because it hasn't been generated (ie. you are trying to delete a message after you send it), you would have to use a react promise.

```php
$channel->send($text)->then(function($new_message) use ($client){
	$message->delete(); //delete the message that triggered the event listener
	$client->addTimer(10, function() use ($new_message) { //do something to $new_message in 10 seconds
		$new_message->delete();
		return true;
	});
	return true;
});
```
If you needed to reference the message ID in the future then there are many different approaches you could take such as saving the channel id and message id to global variables, files, SQL table, etc. and then fetching them again when they're needed.

**Comment by MattMski** [comment]
So I am trying to make a command that deletes any message (of the bots) from a channel on the server (where the bot is on) or through DM (DM with the bot). Is that possible?

**Comment by valzargaming** [comment]
That makes sense to me, and yes that should work. You may need to add an error handler to your code to find out what is going on, or use get_class on each of those variables to make sure they are valid. The only alternative issue I can think of would be related to bot permissions. Bots cannot delete messages sent in a direct message and they need the proper permission to delete messages in a server.

**Comment by MattMski** [comment]
Correct and I understand that. I get the bot permissions as well, I just want the bot to be able to delete messages of its own, not other users. Not sure of how to do that though.

**Comment by valzargaming** [comment]
You would do it the same way. You still won't be able to delete any messages in a direct message.
See lines starting at 173 of https://github.com/valzargaming/Palace/blob/master/messagereactionadd-include.php where I'm getting the ID as stored in a file on line 55.
